# Generated by Django 3.2.2 on 2023-02-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0010_owner_no_of_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='prices',
            field=models.IntegerField(default=0),
        ),
    ]
