# Generated by Django 3.2.2 on 2023-02-20 05:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0011_owner_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='date',
            field=models.DateField(default=datetime.datetime.today, error_messages={'required': 'This field is required.'}),
        ),
        migrations.AddField(
            model_name='owner',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, error_messages={'required': 'This field is required.'}),
        ),
    ]
