# Generated by Django 3.2.2 on 2023-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0012_auto_20230220_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
